//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace Komponenty_app {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(1)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class Arkusz1 : Microsoft.Office.Tools.Excel.WorksheetBase {
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button1;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button2;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button3;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button4;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button5;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button6;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button7;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button8;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button9;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button10;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button11;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button12;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button13;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button14;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button15;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button16;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button17;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button18;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button19;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button20;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button21;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button22;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button23;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button24;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button25;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button26;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button27;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button28;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button29;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button30;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button31;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button32;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button33;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button34;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button35;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button36;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button37;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button38;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button39;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button40;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button41;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button42;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button43;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button44;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button45;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button46;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button47;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button48;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button49;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button50;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button51;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button52;
        
        internal Microsoft.Office.Tools.Excel.Controls.Button button53;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Arkusz1(global::Microsoft.Office.Tools.Excel.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "Arkusz1", "Arkusz1") {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            Globals.Arkusz1 = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.button1 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "24F89F1BC2C4D3245972A06E2A56E86223B082", "24F89F1BC2C4D3245972A06E2A56E86223B082", this, "button1");
            this.button2 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "2EB08E3DE28AEB246B9280EE2D04335EE19682", "2EB08E3DE28AEB246B9280EE2D04335EE19682", this, "button2");
            this.button3 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "3F981613D37167348C43AEE7361EEF328C1E13", "3F981613D37167348C43AEE7361EEF328C1E13", this, "button3");
            this.button4 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "32F50B3273C83534E4239B9D33422246272B33", "32F50B3273C83534E4239B9D33422246272B33", this, "button4");
            this.button5 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "323F5705D30F503423D38C5F31399CC0A35A03", "323F5705D30F503423D38C5F31399CC0A35A03", this, "button5");
            this.button6 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "3BB4DA5DC35315349E53B9453222A0FDE1AD53", "3BB4DA5DC35315349E53B9453222A0FDE1AD53", this, "button6");
            this.button7 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "433AB47044F6E2446F648B36448B51A774CC04", "433AB47044F6E2446F648B36448B51A774CC04", this, "button7");
            this.button8 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "455985A494FFAF442844B4AF40B32BF55227F4", "455985A494FFAF442844B4AF40B32BF55227F4", this, "button8");
            this.button9 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "4FF7075DA4B6CC4497B4A3084882D52131D074", "4FF7075DA4B6CC4497B4A3084882D52131D074", this, "button9");
            this.button10 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "4A34A85F1482DB444884B8354BCC2BA70677F4", "4A34A85F1482DB444884B8354BCC2BA70677F4", this, "button10");
            this.button11 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "431A69E1542802440B74944C45A243F3522F04", "431A69E1542802440B74944C45A243F3522F04", this, "button11");
            this.button12 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "4DEEC2C3D4D25F444A849FA240408DD9F6A624", "4DEEC2C3D4D25F444A849FA240408DD9F6A624", this, "button12");
            this.button13 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "46E265EC64D53C4482C49C224E870DC77D3324", "46E265EC64D53C4482C49C224E870DC77D3324", this, "button13");
            this.button14 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "4C035AF4C459AE443D34A58B4D58AAB1AC6D24", "4C035AF4C459AE443D34A58B4D58AAB1AC6D24", this, "button14");
            this.button15 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "4CD14ED074F47B44917489984B9CC237434EB4", "4CD14ED074F47B44917489984B9CC237434EB4", this, "button15");
            this.button16 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "4A6DA92EA40A3C44B17482304CEE5895B5D064", "4A6DA92EA40A3C44B17482304CEE5895B5D064", this, "button16");
            this.button17 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "5FF8DA5A65F764548505A875505B49449B78C5", "5FF8DA5A65F764548505A875505B49449B78C5", this, "button17");
            this.button18 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "5752D525656E075493759B625580BC0911EE35", "5752D525656E075493759B625580BC0911EE35", this, "button18");
            this.button19 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "6760159A06FE3F6423C6B62F6ED7A84D0D24B6", "6760159A06FE3F6423C6B62F6ED7A84D0D24B6", this, "button19");
            this.button20 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "600EEC785697D864BBB6A8BD69FA5B5B621F26", "600EEC785697D864BBB6A8BD69FA5B5B621F26", this, "button20");
            this.button21 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "61504A838635EE6434968CD36555930A9E9CA6", "61504A838635EE6434968CD36555930A9E9CA6", this, "button21");
            this.button22 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "6103274A96218A6404F6AA2E65414A3BEDA906", "6103274A96218A6404F6AA2E65414A3BEDA906", this, "button22");
            this.button23 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "6F851B16769A2D64A236A30F67B9DFAC7E9EA6", "6F851B16769A2D64A236A30F67B9DFAC7E9EA6", this, "button23");
            this.button24 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "6F741BB6665A7C646106A38A6B4D612EC5F786", "6F741BB6665A7C646106A38A6B4D612EC5F786", this, "button24");
            this.button25 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "7F98FB5917694674D137AFFB78265441D7DC77", "7F98FB5917694674D137AFFB78265441D7DC77", this, "button25");
            this.button26 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "74D88D850709C37441A78A7C7E3F95AC091C07", "74D88D850709C37441A78A7C7E3F95AC091C07", this, "button26");
            this.button27 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "7D7B2C9CD75A7974BDC796097A2ED93E0F1F77", "7D7B2C9CD75A7974BDC796097A2ED93E0F1F77", this, "button27");
            this.button28 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "72E800D3F713AF747F079791713E9267E14327", "72E800D3F713AF747F079791713E9267E14327", this, "button28");
            this.button29 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "74D56423D7A22B742347BCB4791178B60850A7", "74D56423D7A22B742347BCB4791178B60850A7", this, "button29");
            this.button30 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "798CA8C3B7C0C57413F7A1E776B7BB057B5E07", "798CA8C3B7C0C57413F7A1E776B7BB057B5E07", this, "button30");
            this.button31 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "70068CD5077A1F74BC37B41F7BF65AB40E1E67", "70068CD5077A1F74BC37B41F7BF65AB40E1E67", this, "button31");
            this.button32 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "7262A3A4C766C37496B7A36670E2F1612A8B37", "7262A3A4C766C37496B7A36670E2F1612A8B37", this, "button32");
            this.button33 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "7A6EFD2BD79CB074D4F79A0F71B1E3930ECC87", "7A6EFD2BD79CB074D4F79A0F71B1E3930ECC87", this, "button33");
            this.button34 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "7303ED3767712174BB57AFBA7BB92242C605A7", "7303ED3767712174BB57AFBA7BB92242C605A7", this, "button34");
            this.button35 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "85C580D7E881DB84471883378BE5886D8BC6A8", "85C580D7E881DB84471883378BE5886D8BC6A8", this, "button35");
            this.button36 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "800BD8E158826284C9788A7F8A07754300A428", "800BD8E158826284C9788A7F8A07754300A428", this, "button36");
            this.button37 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "83B55834A8655A840FC8BBB48CB72052C5B1D8", "83B55834A8655A840FC8BBB48CB72052C5B1D8", this, "button37");
            this.button38 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "81BEFC9E68BCAF844D288A198142A5B0169798", "81BEFC9E68BCAF844D288A198142A5B0169798", this, "button38");
            this.button39 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "834FF52F48C5BF84609899C087D9683CAAB5D8", "834FF52F48C5BF84609899C087D9683CAAB5D8", this, "button39");
            this.button40 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "8CCDE18BB89E0084B598B2918406F3F94A5768", "8CCDE18BB89E0084B598B2918406F3F94A5768", this, "button40");
            this.button41 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "8260CE84987FFC847A18B53A8EBE273C12F9F8", "8260CE84987FFC847A18B53A8EBE273C12F9F8", this, "button41");
            this.button42 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "841B845F183E7384A0F8A32580F94161979FE8", "841B845F183E7384A0F8A32580F94161979FE8", this, "button42");
            this.button43 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "84936386E88097846588AFBE8E26E64F991F08", "84936386E88097846588AFBE8E26E64F991F08", this, "button43");
            this.button44 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "8D8765CA3833B8843028AE5F8103D4EBC3D0C8", "8D8765CA3833B8843028AE5F8103D4EBC3D0C8", this, "button44");
            this.button45 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "918094A7292B85940F99AB17946E4DB2B227E9", "918094A7292B85940F99AB17946E4DB2B227E9", this, "button45");
            this.button46 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "93CFC841F9D3C594AE69B3A7953DCD0C37B859", "93CFC841F9D3C594AE69B3A7953DCD0C37B859", this, "button46");
            this.button47 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "9907F8F09908C9944F89BCF7926E22F486DB09", "9907F8F09908C9944F89BCF7926E22F486DB09", this, "button47");
            this.button48 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "9B64A41C19FBC294B609ADE19C8E58C74AFB19", "9B64A41C19FBC294B609ADE19C8E58C74AFB19", this, "button48");
            this.button49 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "97BA70DC291F6994F5F997F39602445E89EB49", "97BA70DC291F6994F5F997F39602445E89EB49", this, "button49");
            this.button50 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "9B964B5C89D73994D9A9A8039DD30848FF3589", "9B964B5C89D73994D9A9A8039DD30848FF3589", this, "button50");
            this.button51 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "9BD201EEA9B525944E29A4D39058D171DA4959", "9BD201EEA9B525944E29A4D39058D171DA4959", this, "button51");
            this.button52 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "1FEE8F3B717F5814D1E1A3DC14C4D1EF56C0B1", "1FEE8F3B717F5814D1E1A3DC14C4D1EF56C0B1", this, "button52");
            this.button53 = new Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, this.ItemProvider, this.HostContext, "16973A07E1BDA9149BF1A8FD180B59F6EC6021", "16973A07E1BDA9149BF1A8FD180B59F6EC6021", this, "button53");
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button1.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(238)));
            this.button1.Name = "button1";
            this.button1.Text = "Włącz";
            this.button1.UseVisualStyleBackColor = false;
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button2.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button2.Name = "button2";
            this.button2.Text = "Włącz";
            this.button2.UseVisualStyleBackColor = false;
            // 
            // button3
            // 
            this.button3.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button3.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button3.Name = "button3";
            this.button3.Text = "Włącz";
            this.button3.UseVisualStyleBackColor = false;
            // 
            // button4
            // 
            this.button4.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button4.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button4.Name = "button4";
            this.button4.Text = "Włącz";
            this.button4.UseVisualStyleBackColor = false;
            // 
            // button5
            // 
            this.button5.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button5.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button5.Name = "button5";
            this.button5.Text = "Włącz";
            this.button5.UseVisualStyleBackColor = false;
            // 
            // button6
            // 
            this.button6.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button6.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button6.Name = "button6";
            this.button6.Text = "Włącz";
            this.button6.UseVisualStyleBackColor = false;
            // 
            // button7
            // 
            this.button7.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button7.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button7.Name = "button7";
            this.button7.Text = "Włącz";
            this.button7.UseVisualStyleBackColor = false;
            // 
            // button8
            // 
            this.button8.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button8.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button8.Name = "button8";
            this.button8.Text = "Włącz";
            this.button8.UseVisualStyleBackColor = false;
            // 
            // button9
            // 
            this.button9.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button9.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button9.Name = "button9";
            this.button9.Text = "Włącz";
            this.button9.UseVisualStyleBackColor = false;
            // 
            // button10
            // 
            this.button10.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button10.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button10.Name = "button10";
            this.button10.Text = "Włącz";
            this.button10.UseVisualStyleBackColor = false;
            // 
            // button11
            // 
            this.button11.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button11.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button11.Name = "button11";
            this.button11.Text = "Włącz";
            this.button11.UseVisualStyleBackColor = false;
            // 
            // button12
            // 
            this.button12.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button12.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button12.Name = "button12";
            this.button12.Text = "Włącz";
            this.button12.UseVisualStyleBackColor = false;
            // 
            // button13
            // 
            this.button13.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button13.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button13.Name = "button13";
            this.button13.Text = "Włącz";
            this.button13.UseVisualStyleBackColor = false;
            // 
            // button14
            // 
            this.button14.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button14.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button14.Name = "button14";
            this.button14.Text = "Włącz";
            this.button14.UseVisualStyleBackColor = false;
            // 
            // button15
            // 
            this.button15.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button15.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button15.Name = "button15";
            this.button15.Text = "Włącz";
            this.button15.UseVisualStyleBackColor = false;
            // 
            // button16
            // 
            this.button16.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button16.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button16.Name = "button16";
            this.button16.Text = "Włącz";
            this.button16.UseVisualStyleBackColor = false;
            // 
            // button17
            // 
            this.button17.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button17.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button17.Name = "button17";
            this.button17.Text = "Włącz";
            this.button17.UseVisualStyleBackColor = false;
            // 
            // button18
            // 
            this.button18.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button18.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button18.Name = "button18";
            this.button18.Text = "Włącz";
            this.button18.UseVisualStyleBackColor = false;
            // 
            // button19
            // 
            this.button19.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button19.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button19.Name = "button19";
            this.button19.Text = "Włącz";
            this.button19.UseVisualStyleBackColor = false;
            // 
            // button20
            // 
            this.button20.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button20.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button20.Name = "button20";
            this.button20.Text = "Włącz";
            this.button20.UseVisualStyleBackColor = false;
            // 
            // button21
            // 
            this.button21.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button21.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button21.Name = "button21";
            this.button21.Text = "Włącz";
            this.button21.UseVisualStyleBackColor = false;
            // 
            // button22
            // 
            this.button22.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button22.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button22.Name = "button22";
            this.button22.Text = "Włącz";
            this.button22.UseVisualStyleBackColor = false;
            // 
            // button23
            // 
            this.button23.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button23.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button23.Name = "button23";
            this.button23.Text = "Włącz";
            this.button23.UseVisualStyleBackColor = false;
            // 
            // button24
            // 
            this.button24.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button24.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button24.Name = "button24";
            this.button24.Text = "Włącz";
            this.button24.UseVisualStyleBackColor = false;
            // 
            // button25
            // 
            this.button25.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button25.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button25.Name = "button25";
            this.button25.Text = "Włącz";
            this.button25.UseVisualStyleBackColor = false;
            // 
            // button26
            // 
            this.button26.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button26.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button26.Name = "button26";
            this.button26.Text = "Włącz";
            this.button26.UseVisualStyleBackColor = false;
            // 
            // button27
            // 
            this.button27.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button27.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button27.Name = "button27";
            this.button27.Text = "Włącz";
            this.button27.UseVisualStyleBackColor = false;
            // 
            // button28
            // 
            this.button28.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button28.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button28.Name = "button28";
            this.button28.Text = "Włącz";
            this.button28.UseVisualStyleBackColor = false;
            // 
            // button29
            // 
            this.button29.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button29.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button29.Name = "button29";
            this.button29.Text = "Włącz";
            this.button29.UseVisualStyleBackColor = false;
            // 
            // button30
            // 
            this.button30.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button30.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button30.Name = "button30";
            this.button30.Text = "Włącz";
            this.button30.UseVisualStyleBackColor = false;
            // 
            // button31
            // 
            this.button31.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button31.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button31.Name = "button31";
            this.button31.Text = "Włącz";
            this.button31.UseVisualStyleBackColor = false;
            // 
            // button32
            // 
            this.button32.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button32.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button32.Name = "button32";
            this.button32.Text = "Włącz";
            this.button32.UseVisualStyleBackColor = false;
            // 
            // button33
            // 
            this.button33.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button33.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button33.Name = "button33";
            this.button33.Text = "Włącz";
            this.button33.UseVisualStyleBackColor = false;
            // 
            // button34
            // 
            this.button34.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button34.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button34.Name = "button34";
            this.button34.Text = "Włącz";
            this.button34.UseVisualStyleBackColor = false;
            // 
            // button35
            // 
            this.button35.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button35.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button35.Name = "button35";
            this.button35.Text = "Włącz";
            this.button35.UseVisualStyleBackColor = false;
            // 
            // button36
            // 
            this.button36.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button36.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button36.Name = "button36";
            this.button36.Text = "Włącz";
            this.button36.UseVisualStyleBackColor = false;
            // 
            // button37
            // 
            this.button37.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button37.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button37.Name = "button37";
            this.button37.Text = "Włącz";
            this.button37.UseVisualStyleBackColor = false;
            // 
            // button38
            // 
            this.button38.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button38.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button38.Name = "button38";
            this.button38.Text = "Włącz";
            this.button38.UseVisualStyleBackColor = false;
            // 
            // button39
            // 
            this.button39.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button39.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button39.Name = "button39";
            this.button39.Text = "Włącz";
            this.button39.UseVisualStyleBackColor = false;
            // 
            // button40
            // 
            this.button40.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button40.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button40.Name = "button40";
            this.button40.Text = "Włącz";
            this.button40.UseVisualStyleBackColor = false;
            // 
            // button41
            // 
            this.button41.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button41.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button41.Name = "button41";
            this.button41.Text = "Włącz";
            this.button41.UseVisualStyleBackColor = false;
            // 
            // button42
            // 
            this.button42.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button42.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button42.Name = "button42";
            this.button42.Text = "Włącz";
            this.button42.UseVisualStyleBackColor = false;
            // 
            // button43
            // 
            this.button43.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button43.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button43.Name = "button43";
            this.button43.Text = "Włącz";
            this.button43.UseVisualStyleBackColor = false;
            // 
            // button44
            // 
            this.button44.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button44.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button44.Name = "button44";
            this.button44.Text = "Włącz";
            this.button44.UseVisualStyleBackColor = false;
            // 
            // button45
            // 
            this.button45.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button45.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button45.Name = "button45";
            this.button45.Text = "Włącz";
            this.button45.UseVisualStyleBackColor = false;
            // 
            // button46
            // 
            this.button46.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button46.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button46.Name = "button46";
            this.button46.Text = "Włącz";
            this.button46.UseVisualStyleBackColor = false;
            // 
            // button47
            // 
            this.button47.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button47.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button47.Name = "button47";
            this.button47.Text = "Włącz";
            this.button47.UseVisualStyleBackColor = false;
            // 
            // button48
            // 
            this.button48.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button48.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button48.Name = "button48";
            this.button48.Text = "Włącz";
            this.button48.UseVisualStyleBackColor = false;
            // 
            // button49
            // 
            this.button49.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button49.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button49.Name = "button49";
            this.button49.Text = "Włącz";
            this.button49.UseVisualStyleBackColor = false;
            // 
            // button50
            // 
            this.button50.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button50.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button50.Name = "button50";
            this.button50.Text = "Włącz";
            this.button50.UseVisualStyleBackColor = false;
            // 
            // button51
            // 
            this.button51.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button51.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button51.Name = "button51";
            this.button51.Text = "Włącz";
            this.button51.UseVisualStyleBackColor = false;
            // 
            // button52
            // 
            this.button52.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button52.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button52.Name = "button52";
            this.button52.Text = "Włącz";
            this.button52.UseVisualStyleBackColor = false;
            // 
            // button53
            // 
            this.button53.BackColor = System.Drawing.SystemColors.ControlLight;
            this.button53.Font = new System.Drawing.Font("Microsoft Sans Serif", 7F);
            this.button53.Name = "button53";
            this.button53.Text = "Włącz";
            this.button53.UseVisualStyleBackColor = false;
            // 
            // Arkusz1
            // 
            this.button1.BindingContext = this.BindingContext;
            this.button2.BindingContext = this.BindingContext;
            this.button3.BindingContext = this.BindingContext;
            this.button4.BindingContext = this.BindingContext;
            this.button5.BindingContext = this.BindingContext;
            this.button6.BindingContext = this.BindingContext;
            this.button7.BindingContext = this.BindingContext;
            this.button8.BindingContext = this.BindingContext;
            this.button9.BindingContext = this.BindingContext;
            this.button10.BindingContext = this.BindingContext;
            this.button11.BindingContext = this.BindingContext;
            this.button12.BindingContext = this.BindingContext;
            this.button13.BindingContext = this.BindingContext;
            this.button14.BindingContext = this.BindingContext;
            this.button15.BindingContext = this.BindingContext;
            this.button16.BindingContext = this.BindingContext;
            this.button17.BindingContext = this.BindingContext;
            this.button18.BindingContext = this.BindingContext;
            this.button19.BindingContext = this.BindingContext;
            this.button20.BindingContext = this.BindingContext;
            this.button21.BindingContext = this.BindingContext;
            this.button22.BindingContext = this.BindingContext;
            this.button23.BindingContext = this.BindingContext;
            this.button24.BindingContext = this.BindingContext;
            this.button25.BindingContext = this.BindingContext;
            this.button26.BindingContext = this.BindingContext;
            this.button27.BindingContext = this.BindingContext;
            this.button28.BindingContext = this.BindingContext;
            this.button29.BindingContext = this.BindingContext;
            this.button30.BindingContext = this.BindingContext;
            this.button31.BindingContext = this.BindingContext;
            this.button32.BindingContext = this.BindingContext;
            this.button33.BindingContext = this.BindingContext;
            this.button34.BindingContext = this.BindingContext;
            this.button35.BindingContext = this.BindingContext;
            this.button36.BindingContext = this.BindingContext;
            this.button37.BindingContext = this.BindingContext;
            this.button38.BindingContext = this.BindingContext;
            this.button39.BindingContext = this.BindingContext;
            this.button40.BindingContext = this.BindingContext;
            this.button41.BindingContext = this.BindingContext;
            this.button42.BindingContext = this.BindingContext;
            this.button43.BindingContext = this.BindingContext;
            this.button44.BindingContext = this.BindingContext;
            this.button45.BindingContext = this.BindingContext;
            this.button46.BindingContext = this.BindingContext;
            this.button47.BindingContext = this.BindingContext;
            this.button48.BindingContext = this.BindingContext;
            this.button49.BindingContext = this.BindingContext;
            this.button50.BindingContext = this.BindingContext;
            this.button51.BindingContext = this.BindingContext;
            this.button52.BindingContext = this.BindingContext;
            this.button53.BindingContext = this.BindingContext;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
    }
    
    internal sealed partial class Globals {
        
        private static Arkusz1 _Arkusz1;
        
        internal static Arkusz1 Arkusz1 {
            get {
                return _Arkusz1;
            }
            set {
                if ((_Arkusz1 == null)) {
                    _Arkusz1 = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
    }
}
